/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CaixaRouteImport } from './routes/caixa'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaBarbeiroRouteImport } from './routes/agenda.$barbeiro'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CaixaRoute = CaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaBarbeiroRoute = AgendaBarbeiroRouteImport.update({
  id: '/agenda/$barbeiro',
  path: '/agenda/$barbeiro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRoute
  '/agenda/$barbeiro': typeof AgendaBarbeiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRoute
  '/agenda/$barbeiro': typeof AgendaBarbeiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caixa': typeof CaixaRoute
  '/clientes': typeof ClientesRoute
  '/equipe': typeof EquipeRoute
  '/login': typeof LoginRoute
  '/servicos': typeof ServicosRoute
  '/agenda/$barbeiro': typeof AgendaBarbeiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/caixa'
    | '/clientes'
    | '/equipe'
    | '/login'
    | '/servicos'
    | '/agenda/$barbeiro'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/caixa'
    | '/clientes'
    | '/equipe'
    | '/login'
    | '/servicos'
    | '/agenda/$barbeiro'
  id:
    | '__root__'
    | '/'
    | '/caixa'
    | '/clientes'
    | '/equipe'
    | '/login'
    | '/servicos'
    | '/agenda/$barbeiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaixaRoute: typeof CaixaRoute
  ClientesRoute: typeof ClientesRoute
  EquipeRoute: typeof EquipeRoute
  LoginRoute: typeof LoginRoute
  ServicosRoute: typeof ServicosRoute
  AgendaBarbeiroRoute: typeof AgendaBarbeiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caixa': {
      id: '/caixa'
      path: '/caixa'
      fullPath: '/caixa'
      preLoaderRoute: typeof CaixaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$barbeiro': {
      id: '/agenda/$barbeiro'
      path: '/agenda/$barbeiro'
      fullPath: '/agenda/$barbeiro'
      preLoaderRoute: typeof AgendaBarbeiroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaixaRoute: CaixaRoute,
  ClientesRoute: ClientesRoute,
  EquipeRoute: EquipeRoute,
  LoginRoute: LoginRoute,
  ServicosRoute: ServicosRoute,
  AgendaBarbeiroRoute: AgendaBarbeiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
