/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaBarbeiroRouteImport } from './routes/agenda.$barbeiro'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaBarbeiroRoute = AgendaBarbeiroRouteImport.update({
  id: '/agenda/$barbeiro',
  path: '/agenda/$barbeiro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/agenda/$barbeiro': typeof AgendaBarbeiroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/agenda/$barbeiro': typeof AgendaBarbeiroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipe': typeof EquipeRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/agenda/$barbeiro': typeof AgendaBarbeiroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipe' | '/leads' | '/login' | '/agenda/$barbeiro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipe' | '/leads' | '/login' | '/agenda/$barbeiro'
  id: '__root__' | '/' | '/equipe' | '/leads' | '/login' | '/agenda/$barbeiro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipeRoute: typeof EquipeRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  AgendaBarbeiroRoute: typeof AgendaBarbeiroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$barbeiro': {
      id: '/agenda/$barbeiro'
      path: '/agenda/$barbeiro'
      fullPath: '/agenda/$barbeiro'
      preLoaderRoute: typeof AgendaBarbeiroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipeRoute: EquipeRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  AgendaBarbeiroRoute: AgendaBarbeiroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
